# Classification Naive Bayes

In [16]:
#Assigning features and label variabel
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny',
 'Overcast','Overcast','Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No' ]


In [17]:
#Import labelEncoder
from sklearn import preprocessing

#creating label encoding
le= preprocessing.LabelEncoder()

#Converting string labels into numbers
weather_encode= le.fit_transform(weather)
print(weather_encode)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [18]:
#converting string labels into number 
temp_encoded= le.fit_transform(temp)
label= le.fit_transform(play)

print("temp: ", temp_encoded)
print("label: ", label)

temp:  [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
label:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [19]:
#combining weather and temp into single list of tuple
features = list(zip(weather_encode, temp_encoded))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [20]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#create gaussian Classifier
model = GaussianNB()

#Train the model using training sets
model.fit(features,label)

#predict output
predicted= model.predict([[0,2]]) # 0 : Overcast, 2:Mild
print("Predicted Value: ", predicted)


Predicted Value:  [1]


## Naive Bayes Multiple Labels

In [21]:
#import sklearn dataset library
from sklearn import datasets

loa

NameError: name 'loa' is not defined

# Decision Tree

In [22]:
#load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics


In [23]:
col_names=['Pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']

#load dataset
diabetesDF=pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/diabetes.csv', header=1, names=col_names)


In [24]:
diabetesDF.head()

Pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         1       85  66    29        0  26.6     0.351   31      0
1         8      183  64     0        0  23.3     0.672   32      1
2         1       89  66    23       94  28.1     0.167   21      0
3         0      137  40    35      168  43.1     2.288   33      1
4         5      116  74     0        0  25.6     0.201   30      0

In [25]:
diabetesDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pregnant  767 non-null    int64  
 1   glucose   767 non-null    int64  
 2   bp        767 non-null    int64  
 3   skin      767 non-null    int64  
 4   insulin   767 non-null    int64  
 5   bmi       767 non-null    float64
 6   pedigree  767 non-null    float64
 7   age       767 non-null    int64  
 8   label     767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [26]:
# numer=['pregnant','insulin','bmi','age','glucose','bp','pedigree','label']

for col in col_names:
    diabetesDF[col]=pd.to_numeric(diabetesDF[col], errors='coerce')

In [27]:
diabetesDF.dropna(inplace=True)

In [28]:
diabetesDF

Pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0           1       85  66    29        0  26.6     0.351   31      0
1           8      183  64     0        0  23.3     0.672   32      1
2           1       89  66    23       94  28.1     0.167   21      0
3           0      137  40    35      168  43.1     2.288   33      1
4           5      116  74     0        0  25.6     0.201   30      0
..        ...      ...  ..   ...      ...   ...       ...  ...    ...
762        10      101  76    48      180  32.9     0.171   63      0
763         2      122  70    27        0  36.8     0.340   27      0
764         5      121  72    23      112  26.2     0.245   30      0
765         1      126  60     0        0  30.1     0.349   47      1
766         1       93  70    31        0  30.4     0.315   23      0

[767 rows x 9 columns]

In [29]:
#split dataset in features  and target variable
feature_cols= ['Pregnant','insulin','bmi','age','glucose','bp','pedigree','label']
independent= diabetesDF[feature_cols] #features
dependent = diabetesDF.label #target variable

In [30]:
#split dataset
x_train, x_test, y_train, y_test= train_test_split(independent, dependent, test_size=0.3, random_state=42) # training data 70% and 30% test

In [31]:
#create decision tree classifier object
model= DecisionTreeClassifier()

#Train decision Tree Classifier
trained_model= model.fit(x_train, y_train)

#predict response for test dataset
y_pred = trained_model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1])

In [32]:
print("Accuracy: ", metrics.accuracy_score(y_pred, y_test))

Accuracy:  1.0


### visualizing Decision Trees

In [33]:
import sklearn.tree as tree
from sklearn.externals.six import StringIO
import pydotplus
from IPython.display import Image



/home/dotachin/.local/lib/python3.8/site-packages/sklearn/externals/six.py:28: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  warnings.warn("The module is deprecated in version 0.21 and will be removed "


### iris_petal

In [34]:
import sklearn.datasets as datasets
from sklearn.ensemble import RandomForestClassifier
datasets= datasets.load_iris()


In [35]:
datasets.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [36]:
datasets.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [37]:
irisDF= pd.DataFrame({
    'sepal_length':datasets.data[:, 0],
    'sepal_width':datasets.data[:, 1],
    'petal_length':datasets.data[:, 2],
    'petal_width': datasets.data[:, 3],
    'spesies': datasets.target
    })

In [38]:
irisDF

sepal_length  sepal_width  petal_length  petal_width  spesies
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(irisDF[["sepal_length",
                                                            "sepal_width", 
                                                            "petal_length",
                                                            "petal_width"]],
                                                    irisDF.spesies )


classifier = RandomForestClassifier(n_estimators=50)
classifier = classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)
y_pred

array([2, 2, 1, 0, 2, 0, 1, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 2, 1, 1, 1, 0, 2, 0, 0, 2])

In [40]:
classifier

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [41]:
irisDF= pd.DataFrame({
    'sepal_length':datasets.data[:, 0],
    'petal_length':datasets.data[:, 1],
    'petal_width': datasets.data[:, 2],
    'spesies': datasets.target
    })

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(irisDF[["sepal_length",
                                                            "petal_length",
                                                            "petal_width"
                                                           ]],
                                                    irisDF.spesies )


classifier = RandomForestClassifier(n_estimators=50)
classifier = classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)
y_pred

array([2, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 2, 1, 2, 0, 2, 1, 0, 1, 0, 2, 1,
       2, 2, 1, 1, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2, 0])

In [43]:
metrics.accuracy_score(y_pred, Y_test)

0.9736842105263158

In [44]:
feature_imp= pd.Series(classifier.feature_importances_, index =['sepal_length',
                                                               'petal_length',
                                                               'petal_width',
                                                               ]).sort_values(ascending=False)
feature_imp

petal_width     0.572602
sepal_length    0.294105
petal_length    0.133293
dtype: float64

# SVM (Support Vector Machines)
* Classification approach, dapat digunakan pada klasifikasi dan regresi.
* ide inti dari svm adalah menemukan maximum marginal hyperplane(MMH) yang paling baik membagi dataset menjadi beberapa kelas.

### Loading Data

In [45]:
from sklearn import datasets

#load datasets
cancer = datasets.load_breast_cancer()


### Exploring data

In [46]:
#print names of the 13 features
print("Features: ", cancer.feature_names)

#pring the label type of cancer ('malignant','benign')
print("Label", cancer.target_names)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Label ['malignant' 'benign']


In [47]:
cancer.data.shape

(569, 30)

In [48]:
print(cancer.data[0:5])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-01 2.414

In [49]:
#print cancer label (0:'malignant', 1:'benign')
print(cancer.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

### Splitting data

In [50]:
from sklearn.model_selection import train_test_split

#split dataset into training set and testing set
x_train, x_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3, random_state=109)

### Generating model

In [51]:
#import svm model
from sklearn import svm

#create svm classifier
model = svm.SVC(kernel='linear') #linear kernel
#train the model using train set
model.fit(x_train, y_train)
#predict the response for test dataset
ypred = model.predict(x_test)


### Evaluating Model

In [52]:
# import sklearn metrics module for accuracy calculation
from sklearn import metrics

#model accuracy: how often is the classifer correct?
print("Accuracy", metrics.accuracy_score(y_test, ypred))

Accuracy 0.9649122807017544


In [53]:
# Model precision = what precentage of positive tuples are labeled as such?
print("Precision: ",metrics.precision_score(y_test, ypred))

#model recall = what precentage of positive tuples are labeled as such?
print("recall: ", metrics.recall_score(y_test, ypred))

Precision:  0.9811320754716981
recall:  0.9629629629629629


# Exercise : Multiple algorthim on Dataset

In [54]:
import pandas as pd
import numpy as np

In [55]:
train= pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/Final_Dataset/train.csv')

In [56]:
train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [57]:
train.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [58]:
print("Train Data:")
print(train.isnull().sum(),'\n')

Train Data:
Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64 



In [59]:
train.fillna(train.mean(), inplace=True)
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [60]:
train.Gender.fillna(train.Gender.mode()[0], inplace=True)
train.Married.fillna(train.Married.mode()[0], inplace=True)
train.Dependents.fillna(train.Dependents.mode()[0], inplace=True)
train.Self_Employed.fillna(train.Self_Employed.mode()[0], inplace=True)
train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [61]:
train.Loan_Amount_Term = np.log(train.Loan_Amount_Term)

In [62]:
x=train.drop('Loan_Status',1)
y=train.Loan_Status

In [63]:
x=pd.get_dummies(x)
train=pd.get_dummies(train)
x.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162          5.886104   
1             4583             1508.0  128.000000          5.886104   
2             3000                0.0   66.000000          5.886104   
3             2583             2358.0  120.000000          5.886104   
4             6000                0.0  141.000000          5.886104   

   Credit_History  Loan_ID_LP001002  Loan_ID_LP001003  Loan_ID_LP001005  \
0             1.0                 1                 0                 0   
1             1.0                 0                 1                 0   
2             1.0                 0                 0                 1   
3             1.0                 0                 0                 0   
4             1.0                 0                 0                 0   

   Loan_ID_LP001006  Loan_ID_LP001008  ...  Dependents_1  Dependents_2  \
0                 0                 0  ...             0             0   
1                 0                 0  ...             1             0   
2                 0                 0  ...             0             0   
3                 1                 0  ...             0             0   
4                 0                 1  ...             0             0   

   Dependents_3+  Education_Graduate  Education_Not Graduate  \
0              0                   1                       0   
1              0                   1                       0   
2              0                   1                       0   
3              0                   0                       1   
4              0                   1                       0   

   Self_Employed_No  Self_Employed_Yes  Property_Area_Rural  \
0                 1                  0                    0   
1                 1                  0                    1   
2                 0                  1                    0   
3                 1                  0                    0   
4                 1                  0                    0   

   Property_Area_Semiurban  Property_Area_Urban  
0                        0                    1  
1                        0                    0  
2                        0                    1  
3                        0                    1  
4                        0                    1  

[5 rows x 634 columns]

In [64]:
y.head()

0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_cv, y_train, y_cv= train_test_split(x, y, test_size=0.2)

In [72]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train, y_train)


/home/dotachin/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
pred_cv = model.predict(x_cv)

In [69]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print("acc score: ", metrics.accuracy_score(y_cv, pred_cv))
matrix= confusion_matrix(y_cv, pred_cv)
print(matrix)


acc score:  0.8048780487804879
[[19 20]
 [ 4 80]]


In [70]:
# DECISION TREE ALGORITHM
from sklearn import tree
dt=tree.DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [73]:
pred_cv1=dt.predict(x_cv)

In [75]:
print("acc: ",metrics.accuracy_score(y_cv, pred_cv1))
matrix1 = confusion_matrix(y_cv, pred_cv1)
print(matrix1)

acc:  0.7723577235772358
[[23 16]
 [12 72]]


In [76]:
# SUPPORT VECTOR MACHINES (SVM)
from sklearn import svm
svm_model = svm.SVC()
svm_model.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [77]:
pred_cv2=svm_model.predict(x_cv)
print("Acc: ", metrics.accuracy_score(y_cv, pred_cv2))
matrix2= confusion_matrix(y_cv, pred_cv2)
print(matrix2)

Acc:  0.6829268292682927
[[ 0 39]
 [ 0 84]]


In [78]:
# Random Forest Algorithm
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier()
rf_model.fit(x_train, y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [80]:
pred_cv3=rf_model.predict(x_cv)
print("acc: ", metrics.accuracy_score(y_cv, pred_cv3))
matrix3 = confusion_matrix(y_cv, pred_cv3)
print(matrix3)

acc:  0.8211382113821138
[[18 21]
 [ 1 83]]


In [81]:
# NAIVE BAYES ALGORITHM
from sklearn.naive_bayes import GaussianNB
nb_model= GaussianNB()
nb_model.fit(x_train, y_train)
pred_cv4= nb_model.predict(x_cv)
print("acc: ", metrics.accuracy_score(y_cv, pred_cv4))
matrix4= confusion_matrix(y_cv, pred_cv4)
print(matrix4)

acc:  0.8292682926829268
[[20 19]
 [ 2 82]]


In [82]:
# K-NEAREST NEIGHBOR ALGORITHM
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
KNN.fit(x_train, y_train)
pred_cv5= KNN.predict(x_cv)
print("ACC: ", metrics.accuracy_score(y_cv, pred_cv5))
matrix5 = confusion_matrix(y_cv, pred_cv5)
print(matrix5)

ACC:  0.6260162601626016
[[ 9 30]
 [16 68]]


In [83]:
print("Logistik Regression: ", accuracy_score(y_cv, pred_cv))
print("Decision Tree: ", accuracy_score(y_cv, pred_cv1))
print("SVM: ", accuracy_score(y_cv, pred_cv2))
print("Random Forest: ", accuracy_score(y_cv, pred_cv3))
print("Naive Bayes: ", accuracy_score(y_cv, pred_cv4))
print("KNN: ", accuracy_score(y_cv, pred_cv5))

Logistik Regression:  0.8048780487804879
Decision Tree:  0.7723577235772358
SVM:  0.6829268292682927
Random Forest:  0.8211382113821138
Naive Bayes:  0.8292682926829268
KNN:  0.6260162601626016


In [85]:
prediction = pd.DataFrame(pred_cv4, columns=['predictions']).to_csv('H8_NB_Credit_Prediction.csv')