In [2]:
import numpy as np
myArray = np.array([1,2,3,4,5,6])
myArray

array([1, 2, 3, 4, 5, 6])

### Trying some arithmetic operator in  array

In [3]:
myList = [1,2,3,4,5,6]
mulList = myList*5
mulArray = myArray*5

print(mulArray)
print(mulList)

[ 5 10 15 20 25 30]
[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [9]:
addArray = myArray + 5
print(addArray)
divArray = myArray / 5
print(divArray)
subArray = myArray - 5
print(subArray)


[ 6  7  8  9 10 11]
[0.2 0.4 0.6 0.8 1.  1.2]
[-4 -3 -2 -1  0  1]


In [15]:
myArr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
myArr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
print(myArr.shape)
print(type(myArr))

(3, 4)
<class 'numpy.ndarray'>


In [17]:
#try to get 8
print(myArr[2,0])

9


In [33]:
#ambil rentang array 
# print(myArr[0:2,1:3])
print(myArr[0:,1:3])


[[ 2  3]
 [ 6  7]
 [10 11]]


In [34]:
print(myArr[0:][1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
#import data.csv
myStudentData = np.genfromtxt("./data.csv", skip_header =1, delimiter=',',filling_values =70)

In [40]:
myStudentData

array([[75., 70., 80., 30.],
       [90., 76., 87., 90.],
       [78., 70., 79., 67.],
       [90., 70., 78., 89.]])

In [42]:
maxInClass = np.amax(myStudentData, axis=0)
print(maxInClass)

[90. 76. 87. 90.]


In [43]:
avStudentPerMapel = np.mean(myStudentData, axis=0)
print(avStudentPerMapel)

[83.25 71.5  81.   69.  ]


In [59]:
myStudentData = np.append(myStudentData,[[50,68,90,67]],axis=0)

In [60]:
myStudentData

array([[75., 70., 80., 30.],
       [90., 76., 87., 90.],
       [78., 70., 79., 67.],
       [90., 70., 78., 89.],
       [50., 68., 90., 67.]])

In [61]:
myStudentData = np.delete(myStudentData,[4],axis=0)
myStudentData

array([[75., 70., 80., 30.],
       [90., 76., 87., 90.],
       [78., 70., 79., 67.],
       [90., 70., 78., 89.]])

In [63]:
newShape = myStudentData.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [65]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [67]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

### 1D to 2D

In [78]:
Array1D = np.array([1,2,3,4,5,4])
print("1D array: ",Array1D)
Array2D = Array1D.reshape(2,3)
print("1d to 2d: ",Array2D)
backto1D = Array2D.reshape(1,6)[0]
print("back to 1d: ",backto1D)

1D array:  [1 2 3 4 5 4]
1d to 2d:  [[1 2 3]
 [4 5 4]]
back to 1d:  [1 2 3 4 5 4]


In [80]:
array_1 = np.array([
    [1,2,3],
    [4,5,6]
])
array_2 = np.array([
    [3,4,6],
    [6,7,8]
])
array_3 = np.array([
    [3,4],
    [5,6]
])

# Vstack
v_stack = np.vstack((array_1,array_2))
h_stack = np.hstack((array_1,array_2))
h_stackArr3 = np.hstack((array_1,array_3))

In [81]:
print(v_stack)
print(h_stack)
print(h_stackArr3)

[[1 2 3]
 [4 5 6]
 [3 4 6]
 [6 7 8]]
[[1 2 3 3 4 6]
 [4 5 6 6 7 8]]
[[1 2 3 3 4]
 [4 5 6 5 6]]
